server:
    port: 9005
spring:
    application:
        name: profile-service
    data:
        mongodb:
            uri: mongodb://thanh:123456@localhost:27017/microservice

idp:
    url: http://localhost:8180
    client-id: laptrinhfullstack
    client-secret: dRdUaA1lgMVYmKqoCl3g4cUtql05Fj47
    realm: laptrinhfullstack
